on:
  push:
  pull_request:

name: CI

jobs:
  build:
    name: Build GitBook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Build
        uses: docker://yeasy/docker_practice
        with:
          args: build
      - name: vuepress
        run: |
          sudo rm -rf _book
          npm i vuepress --save-dev
          npm i
          npm run vuepress:build
          cp -r . .vuepress/dist/ || true
          find .vuepress/dist -name "*.md" -delete
          echo "vuepress.docker-practice.com" > .vuepress/dist/CNAME
      - name: Upload Vuepress dist
        uses: docker://pcit/pages
        if: github.repository == 'docker-practice/docker_practice'
        env:
          PCIT_EMAIL: khs1994@khs1994.com
          PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
          PCIT_GIT_URL: github.com/docker-practice/vuepress
          PCIT_KEEP_HISTORY: "true"
          PCIT_LOCAL_DIR: .vuepress/dist
          PCIT_MESSAGE: Sync from yeasy/docker_practice@${{github.sha}} by PCIT
          PCIT_TARGET_BRANCH: master
          PCIT_USERNAME: khs1994
      - name: Set coding.net CNAME
        run: |
          echo "vuepress.mirror.docker-practice.com" > .vuepress/dist/CNAME
      - name: Upload Vuepress dist to coding.net
        uses: docker://pcit/pages
        if: github.repository == 'docker-practice/docker_practice'
        env:
          PCIT_EMAIL: khs1994@khs1994.com
          PCIT_GIT_TOKEN: ${{ secrets.CODING_GIT_TOKEN }}
          PCIT_GIT_URL: e.coding.net/dpsigs/docker_practice
          PCIT_KEEP_HISTORY: "true"
          PCIT_LOCAL_DIR: .vuepress/dist
          PCIT_MESSAGE: Sync from yeasy/docker_practice@${{github.sha}} by PCIT
          PCIT_TARGET_BRANCH: master
          PCIT_USERNAME: ptt0xjqzbke3
